Revert "CI: run Go tests in one build"
This reverts commit db6145d41e704c31387defa9523cb87c7dc56e76.

Conflicts:
	.travis.yml
	appveyor.yml

Tests do not work out-of-box in any CI.

Progress with AppVeyor:

    .\issue3775.go:53:2: error: 'usleep' is deprecated
    (declared at c:\mingw\include\unistd.h:130)
    [-Werror=deprecated-declarations]
    https://ci.appveyor.com/project/starius/gohere/build/1.0.17

Linux and OSX builds on Travis also fail in tests:

    FAIL: TestLldbPython (6.05s)
    runtime-lldb_test.go:182: Unexpected lldb output:

    FAIL: TestGetfsstat (0.00s)
    syscall_bsd_test.go:31: an empty Statfs_t struct was returned